coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "__tests__/"  # only include coverage in "__tests__/" folder
      api:  # declare a new status context "app"
        paths: "!__tests__/"  # remove all files in "__tests__/"