version: '3.6'
services:
   database:
      image: postgres
      restart: always
      volumes:
         - ./db-init:/docker-entrypoint-initdb.d
         - postgres_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      env_file:
         - ./.env

   test-database:
    image: postgres
    restart: always
    volumes:
       - ./db-init:/docker-entrypoint-initdb.d
    ports:
        - 45758:5432
    env_file:
         - ./.env

   web-server:
      build:
         context: .
         dockerfile: Dockerfile
      image: brewhops-api_dev
      restart: always
      links:
         - 'database'
      volumes:
        - ./dist:/user/dist
      environment:
         PORT: 1234
         PGHOST: 'database'
         TEST_PG_PORT: 5432
         TEST_PG_HOST: 'test-database'
         NODE_ENV: '${NODE_ENV}'
      ports:
         - 1234:1234
         - 9222:9222
      env_file:
         - ./.env
      depends_on:
         - database

volumes:
  postgres_data:
    name: brewhops-postgres-data_dev
    driver: local
