version: '3.6'
services:
   database:
      image: postgres
      restart: always
      environment:
         POSTGRES_PASSWORD: ${PGPASSWORD}
         POSTGRES_USER: ${PGUSER}
         POSTGRES_DB: ${PGDATABASE}
      volumes:
         - ./db-init:/docker-entrypoint-initdb.d
         - postgres_data:/var/lib/postgresql/data
      ports:
        - 5432:5432
   web-server:
      build: .
      image: brewhops-api
      restart: always
      links:
         - 'database'
      environment:
         PORT: 1234
         PGPASSWORD: ${PGPASSWORD}
         PGUSER: ${PGUSER}
         PGDATABASE: ${PGDATABASE}
         PGHOST: 'database'
      ports:
         - 1234:1234
      depends_on:
         - database


volumes:
  postgres-data:
    name: brewhops-postgress-data
