node_defaults: &node
  docker:
    - image: circleci/node

dev_filter: &devOnly
  branches:
    only: dev

get_latest_version: &getVersion
  name: Set TAG_VERSION and update PATH
  command: >
    echo 'export TAG_VERSION=$((git describe --tags $(git rev-list
    --tags --max-count=1)) | cut -c 2-)' >> $BASH_ENV
    source $BASH_ENV

version: 2
jobs:
  build:
    <<: *node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/project
          paths: 
            - node_modules
      # - run: npm run tsc
        
  unit_tests:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run unit tests
          command: npm run test-ci