node_defaults: &node
  docker:
    - image: circleci/node

dev_filter: &devOnly
  branches:
    only: dev

get_latest_version: &getVersion
  name: Set TAG_VERSION and update PATH
  command: >
    echo 'export TAG_VERSION=$((git describe --tags $(git rev-list
    --tags --max-count=1)) | cut -c 2-)' >> $BASH_ENV
    source $BASH_ENV

version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    <<: *node
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/project
          paths: 
            - node_modules
  unit_tests:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Run unit tests
          command: npm test
  coverage:
    <<: *node
    steps:
      - codecov_upload:
        file: ../coverage/coverage-final.json
        token: 563c370f-9077-4e0b-8903-ddc14594f80f

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - unit_tests:
          requires:
            - build